name: demo_gemin
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  flutter_gemini: ^3.0.0
  # path: ^1.8.0
assets:
  - .env

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
